import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="lg:flex">
          <Sidebar />
          <div className="flex-1">
            <Header />
            <main className="bg-gray-100">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
